name: Generate Site

on:
  # commit on master branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    env:
      TOKEN: ${{ secrets.TOKEN }}  # GitHub Personal Access Token，需要在仓库的 Secrets 中设置
    steps:
      - name: Echo time in Asia/Shanghai
        run: TZ=Asia/Shanghai date
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Generate
        run: |
          cd .github/_site
          npm install
          npm run build

          git config --global user.name "bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "bot: generate"
          git push origin main
